### ISSUE TITLE
Error when the second param (options) is missing

### ISSUE THREAD

**Issue by giyohm** [qwantix/qwx#1]
The readme documentation shows how to use qwx with the following example:

``` js
require('qwx')('myApp')
    .option('appDir', 'src' )
```

It fails immediately with the following error:

``` sh
/node_modules/qwx/index.js:372
  if( options.scope && options.scope instanceof Qwx ) {
             ^

TypeError: Cannot read property 'scope' of undefined
```

The error message is self explanatory.
This second parameter, "options", is not document and it may be a good idea to show an alternative example with it and to clarify that it can be the same kind of object that in the "options" method, with some or all of the following properties.

``` javascript
{
  appDir: '.',
  appRoot: null,
  mask: /^[^._]/, // Ignore file start with "." or "_",
  maxDepth: 15,
  debug: false,
  forkRespawn: false,
  scope: global
}
```

**Comment by qwantix** [comment]
Hi!

Thank for your report, issue are now fixed on master.

The fix will be available in version 0.3.0

I will update the doc about options later, good idea!

Thank for your feedback.
